FROM node:alpine
# create & set working directory
RUN mkdir -p /server
WORKDIR /server
# copy source files
COPY . /server
# install dependencies
# RUN npm cache clean --force 
RUN npm install -g @nrwl/nx
RUN npm install --legacy-peer-deps
# start app
ENV NODE_OPTIONS="--max_old_space_size=8192"
RUN npx nx build react-test
EXPOSE 3000
CMD npm run deploy:userepx
