apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: platformx-userexp-nx
  name: platformx-userexp-nx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: platformx-userexp-nx
  template:
    metadata:
      labels:
        app: platformx-userexp-nx
    spec:
      containers:
        - name: platformx-userexp-nx
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          resources:
            limits:
              cpu: "4"
              memory: 12Gi
            requests:
              cpu: "3"
              memory: 8Gi
          env:
            - name: NEXT_GA_ID
              valueFrom:
                configMapKeyRef:
                  key: NEXT_GA_ID
                  name: hep-user-experience-ui-config
            - name: NEXT_GTM_ID
              valueFrom:
                configMapKeyRef:
                  key: NEXT_GTM_ID
                  name: hep-user-experience-ui-config
            - name: NEXT_PUBLISH_APP_URL
              valueFrom:
                configMapKeyRef:
                  key: NEXT_PUBLISH_APP_URL
                  name: hep-user-experience-ui-config
            - name: NEXT_PUBLISH_API_URL
              valueFrom:
                configMapKeyRef:
                  key: NEXT_PUBLISH_API_URL
                  name: hep-user-experience-ui-config
            - name: NEXT_PUBLISH_API_URL_GENERIC
              valueFrom:
                configMapKeyRef:
                  key: NEXT_PUBLISH_API_URL_GENERIC
                  name: hep-user-experience-ui-config
            - name: NEXT_API_URL
              valueFrom:
                configMapKeyRef:
                  key: NEXT_API_URL
                  name: hep-user-experience-ui-config
            - name: NEXT_BLOGS_API
              valueFrom:
                configMapKeyRef:
                  key: NEXT_BLOGS_API
                  name: hep-user-experience-ui-config
            - name: NEXT_GOOGLE_SEARCH_VERIFICATION
              valueFrom:
                configMapKeyRef:
                  key: NEXT_GOOGLE_SEARCH_VERIFICATION
                  name: hep-user-experience-ui-config
            - name: NEXT_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  key: NEXT_CLIENT_ID
                  name: hep-user-experience-ui-config
            - name: NEXT_GRANT_TYPE
              valueFrom:
                configMapKeyRef:
                  key: NEXT_GRANT_TYPE
                  name: hep-user-experience-ui-config
            - name: NEXT_REALM
              valueFrom:
                configMapKeyRef:
                  key: NEXT_REALM
                  name: hep-user-experience-ui-config
            - name: NEXT_LOGOUT
              valueFrom:
                configMapKeyRef:
                  key: NEXT_LOGOUT
                  name: hep-user-experience-ui-config
            - name: NEXT_AUTH
              valueFrom:
                configMapKeyRef:
                  key: NEXT_AUTH
                  name: hep-user-experience-ui-config
            - name: NEXT_SESSION_VERIFY
              valueFrom:
                configMapKeyRef:
                  key: NEXT_SESSION_VERIFY
                  name: hep-user-experience-ui-config
            - name: NEXT_SESSION
              valueFrom:
                configMapKeyRef:
                  key: NEXT_SESSION
                  name: hep-user-experience-ui-config
            - name: NEXT_ELASTIC_APM_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  key: NEXT_ELASTIC_APM_SERVER_URL
                  name: apm-config
            - name: NEXT_ELASTIC_APM_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  key: NEXT_ELASTIC_APM_ENVIRONMENT
                  name: apm-config
            - name: NEXT_ELASTIC_APM_TRACING
              valueFrom:
                configMapKeyRef:
                  key: NEXT_ELASTIC_APM_TRACING
                  name: apm-config
            - name: NEXT_GEOLOCATION_API_URL
              valueFrom:
                configMapKeyRef:
                  key: NEXT_GEOLOCATION_API_URL
                  name: hep-user-experience-ui-config
            - name: NEXT_GEOLOCATION_API_KEY
              valueFrom:
                configMapKeyRef:
                  key: NEXT_GEOLOCATION_API_KEY
                  name: hep-user-experience-ui-config
            - name: NEXT_GCP_URL
              valueFrom:
                configMapKeyRef:
                  key: NEXT_GCP_URL
                  name: hep-user-experience-ui-config
            - name: NEXT_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  key: NEXT_BUCKET_NAME
                  name: hep-user-experience-ui-config
            - name: NEXT_SNOWPLOW_APP_ID
              valueFrom:
                configMapKeyRef:
                  key: NEXT_SNOWPLOW_APP_ID
                  name: hep-user-experience-ui-config
            - name: NEXT_SNOWPLOW_COLLECTOR_URL
              valueFrom:
                configMapKeyRef:
                  key: NEXT_SNOWPLOW_COLLECTOR_URL
                  name: hep-user-experience-ui-config
            - name: NEXT_CLUSTER_API_URL
              valueFrom:
                configMapKeyRef:
                  key: NEXT_CLUSTER_API_URL
                  name: hep-user-experience-ui-config
            - name: NEXT_USER_SERVICE_APP_URL
              valueFrom:
                configMapKeyRef:
                  key: NEXT_USER_SERVICE_APP_URL
                  name: hep-user-experience-ui-config
            - name: NEXT_SITE_HOST
              valueFrom:
                configMapKeyRef:
                  key: NEXT_SITE_HOST
                  name: hep-user-experience-ui-config
            - name: NEXT_RPI_PUBLISH_ID
              valueFrom:
                configMapKeyRef:
                  key: NEXT_RPI_PUBLISH_ID
                  name: hep-user-experience-ui-config
            - name: NEXT_RPI_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  key: NEXT_RPI_CLIENT_ID
                  name: hep-user-experience-ui-config
            - name: NEXT_RPI_AUTH_KEY
              valueFrom:
                configMapKeyRef:
                  key: NEXT_RPI_AUTH_KEY
                  name: hep-user-experience-ui-config
            - name: NEXT_RPI_VIEW_NAME
              valueFrom:
                configMapKeyRef:
                  key: NEXT_RPI_VIEW_NAME
                  name: hep-user-experience-ui-config
            - name: NEXT_LOYALTY_PORTAL_END_POINT
              valueFrom:
                configMapKeyRef:
                  key: NEXT_LOYALTY_PORTAL_END_POINT
                  name: hep-user-experience-ui-config
            - name: NEXT_LOYALTY_END_POINT
              valueFrom:
                configMapKeyRef:
                  key: NEXT_LOYALTY_END_POINT
                  name: hep-user-experience-ui-config
            - name: NEXT_DELIVERY_ENGINE
              valueFrom:
                configMapKeyRef:
                  key: NEXT_DELIVERY_ENGINE
                  name: hep-user-experience-ui-config
            - name: NEXT_SNOWPLOW_PLACE_ORDER_IMPRESSIONS
              valueFrom:
                configMapKeyRef:
                  key: NEXT_SNOWPLOW_PLACE_ORDER_IMPRESSIONS
                  name: hep-user-experience-ui-config
            - name: NEXT_PAGE_IMPRESSIONS_SCHEMA
              valueFrom:
                configMapKeyRef:
                  key: NEXT_PAGE_IMPRESSIONS_SCHEMA
                  name: hep-user-experience-ui-config
            - name: NEXT_SNOWPLOW_PRELEM_IMPRESSIONS
              valueFrom:
                configMapKeyRef:
                  key: NEXT_SNOWPLOW_PRELEM_IMPRESSIONS
                  name: hep-user-experience-ui-config
            - name: NEXT_SNOWPLOW_CLICK_IMPRESSIONS
              valueFrom:
                configMapKeyRef:
                  key: NEXT_SNOWPLOW_CLICK_IMPRESSIONS
                  name: hep-user-experience-ui-config
            - name: NEXT_SNOWPLOW_REGISTER_USER_IMPRESSIONS
              valueFrom:
                configMapKeyRef:
                  key: NEXT_SNOWPLOW_REGISTER_USER_IMPRESSIONS
                  name: hep-user-experience-ui-config
