export { default as CATSvg } from './cat.png'
export { default as German } from './de_flag.png'
export { default as English } from './en_flag.png'
export { default as Franch } from './fr_flag.png' //fr_flag.png

export { default as fbGray } from './fb-gray.png'
export { default as fbGreen } from './fb-green.png'
export { default as inGray } from './in-gray.png'
export { default as inGreen } from './in-green.png'

export { default as Guideline_Img1 } from './Guideline_Img1.png'
export { default as Guideline_Img2 } from './Guideline_Img2.png'
export { default as GuidelineImage } from './Guideline_image.png'
export { default as SSGuideline } from './SS_Guideline.png'
export { default as avtarImg } from './avatar.png'
export { default as check_circle } from './check_circle.png'
export { default as description_black } from './description_black.png'
export { default as LadyImage } from './lady_Image.svg'
export { default as Logo } from './logo.png'
export { default as NoResults } from './no-results.png'
export { default as successGif } from './success.gif'
