name: CI

on:
  push:
    branches:
      - develop
  pull_request:
env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: true

permissions:
  actions: read
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: "npm"
      - run: npm install --force
      - run: npm run affected:build -- --base=main --head=HEAD --parallel
  agent1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bahmutov/npm-install@v1.4.5
      - run: npx nx cloud start-agent --token ${{ secrets.NX_CLOUD_AGENT_TOKEN }}
  agent2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bahmutov/npm-install@v1.4.5
      - run: npx nx cloud start-agent --token ${{ secrets.NX_CLOUD_AGENT_TOKEN }}
      - run: npx nx cloud stop-all-agents
       
      # Enable distribution
      # The "--stop-agents-after" is optional, but allows idle agents to shut down once the "e2e-ci" targets have been requested
      # - run: npx nx-cloud start-ci-run --distribute-on="5 linux-medium-js" --stop-agents-after="e2e-ci"

      # - uses: nrwl/nx-set-shas@v4.0.4

      # Create a dynamic branch
      # - name: Create dynamic branch
      #   run: |
      #     branch_name="develop-$(date +%Y-%m-%d-%H-%M-%S)"
      #     git branch --track $branch_name origin/develop

      # Run affected builds
      - run: npx nx affected -t build authoring-web --parallel=10

      # Additional commented-out code
      # - run: npx nx-cloud record -- --base=develop -- nx format:check
      # - run: npx nx build authoring-web --parallel=10
      # - run: git branch --track develop origin/develop
      # - run: npx nx affected -t build authoring-web --base=main --head=HEAD
