name: test-nx
on:
  push:
    branches:
      - develop
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  authoring-ui:
    name: authoring-ui
    runs-on: ubuntu-16core-64GB
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set env vars(develop)
        if: endsWith(github.ref, '/develop')
        run: |
          echo "PROJECT_ID=PROJECT_ID_$(echo ${{github.ref_name}} | tr '[:lower:]' '[:upper:]')" >> $GITHUB_ENV

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Restore cached npm dependencies
        id: cache-dependencies-restore
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: npm-dependencies-${{ hashFiles('package-lock.json') }}

      - name: Install Dependencies
        run: npm i --legacy-peer-deps

      - name: Setup Nx Cloud
        run: npx nx connect --organization=hcl-x --token ${{ secrets.NX_CLOUD_TOKEN }}
        env:
          gh_token: ${{ secrets.gh_token }}

      - uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: develop

      - name: Record Nx Cloud Actions and Execute Nx Commands
        run: npx nx affected --target=build --parallel --base=origin/develop --head=HEAD --apps=authoring-web
        env:
          gh_token: ${{ secrets.gh_token }}

  deploy-authoring-ui:
    name: Deploy to GCP Engine
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Project ID from Secrets
        run: echo "PROJECT_ID= ${{ secrets.GCP_PROJECT_ID }}" >> $GITHUB_ENV

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.4.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy to GCP Engine
        run: gcloud app deploy --version=1

  user-experience-ui:
    name: user-experience-ui
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-16core-64GB
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install Dependencies
        run: npm i --legacy-peer-deps

      - name: Setup Nx Cloud
        run: npx nx connect --organization=hcl-x --token ${{ secrets.NX_CLOUD_TOKEN }}

      - name: Record Nx Cloud Actions and Execute Nx Commands
        run: npx nx affected --base=develop --head=HEAD --target=build
