name: test-nx
on:
  push:
    branches:
      - develop
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  authoring-ui:
    name: authoring-ui
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-16core-64GB
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install Dependencies
        run: npm i --legacy-peer-deps

      - name: Setup Nx Cloud
        run: npx nx connect --organization=hcl-x --token ${{ secrets.NX_CLOUD_TOKEN }}

      - uses: nrwl/nx-set-shas@v3

      - name: Record Nx Cloud Actions and Execute Nx Commands
        run: npx nx-cloud record -- npx nx affected --base=develop --head=HEAD --target=build --with-deps --clear-cache

  user-experience-ui:
    name: user-experience-ui
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-16core-64GB
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install Dependencies
        run: npm i --legacy-peer-deps

      - name: Setup Nx Cloud
        run: npx nx connect --organization=hcl-x --token ${{ secrets.NX_CLOUD_TOKEN }}

      - name: Record Nx Cloud Actions and Execute Nx Commands
        run: npx nx-cloud record -- npx nx affected --base=develop --target=build
